name: build.yml
on:
    push:
        branches:
          - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Purge jsdelivr CDN
        run: |
          for file in $(ls); do
            echo "Purging $file"          
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/${file}"
          done